{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sing-box.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "sing-box.labels" . | nindent 4 }}
  {{- with (merge .Values.serviceAccount.annotations .Values.commonAnnotations) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
