apiVersion: v1
kind: Service
metadata:
  name: {{ include "sing-box.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "sing-box.labels" . | nindent 4 }}
  {{- with (merge .Values.service.annotations .Values.commonAnnotations) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxy
      port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector: {{- include "sing-box.selectorLabels" . | nindent 4 }}
