replicaCount: 1

persistence:
  enabled: false

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
