apiVersion: v1
kind: Service
metadata:
  name: {{ include "s-ui.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "s-ui.labels" . | nindent 4 }}
  {{- with (merge .Values.service.annotations .Values.commonAnnotations) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: panel
      port: {{ .Values.service.panel.port }}
      targetPort: panel
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.panel.nodePort }}
      nodePort: {{ .Values.service.panel.nodePort }}
      {{- end }}
    - name: subscription
      port: {{ .Values.service.subscription.port }}
      targetPort: subscription
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.subscription.nodePort }}
      nodePort: {{ .Values.service.subscription.nodePort }}
      {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector: {{- include "s-ui.selectorLabels" . | nindent 4 }}
