name: Release Charts

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Copy artifacthub-repo.yml to gh-pages
        run: |
          ARTIFACT_FILE="$GITHUB_WORKSPACE/artifacthub-repo.yml"
          git fetch origin gh-pages --depth=1 || true
          git checkout gh-pages
          cp "$ARTIFACT_FILE" artifacthub-repo.yml
          git add artifacthub-repo.yml
          git diff --staged --quiet || git commit -m "Update artifacthub-repo.yml"
          git push origin gh-pages
